eps_human = [
    "Elder wearing a wide-brimmed hat",
    "A man",
    "A woman",
    "An elder",
    "A teeneger",
    "A boy",
    "A girl",
    "A policeman",
    "A priest",
    "A nurse",
    "A doctor",
    "A cowboy"
]
eps_action = [
    "play with a cat",
    "play with a dog",
    "play a guitar",
    "write in a notebook",
    "carry a basket of fruit",
    "drinking water",
    "wipe away tears",
    "make a telephone call",
    "eat an apple",
    "dance to the music",
    "arrange hair with hands",
    "count money",
    "scratch head",
    "sitting down",
    "standing up",
    "holding an umbrella",

]

eps_background = [
    "on the grassy meadow",
    "at the train platform",
    "by the traffic light",
    "at the bus stop",
    "in the living room",
    "at the coffee shop",
    "by the roadside curb",
    "in the school hallway",
    "on the rooftop terrace",
    "in the kitchen corner",
    "at the airport gate",
    "by the riverbank path",
    "on the sandy beach",
    "in the park pavilion",
    "at the library entrance",
    "in the grocery aisle",
    "on the playground swings",
    "at the gas station",
    "in the movie theater",
    "at the hotel lobby",
    "on the forest trail",
    "in the hotel room",
    "at the car showroom",
    "on the bike lane",
    "at the city fountain",
    "in the art gallery",
    "on the church steps",
    "at the hospital ward",
    "by the garden gate",
    "on the fishing pier",
    "in the coffee queue",
    "at the poolside lounge",
    "on the mountain summit",
    "in the yoga studio",
    "at the convention center",
    "on the tennis court",
    "in the concert hall",
    "at the soccer stadium",
    "on the running track",
    "in the waiting room",
    "at the subway entrance",
    "on the hiking path",
    "in the flower market",
    "at the night market",
    "on the skateboard ramp",
    "in the music studio",
    "at the farmer’s market",
    "on the ferry deck",
    "in the wine cellar",
    "at the bakery counter",
    "on the hotel balcony",
    "in the dance studio",
    "at the fire escape",
    "on the golf course",
    "in the bus terminal",
    "on the airport tarmac",
    "at the wedding venue",
    "on the bookstore floor",
    "on the beach boardwalk",
    "in the hospital waiting area",
    "at the university campus",
    "on the bridge railing",
    "in the mountain cabin",
    "at the zoo entrance",
    "on the skating rink",
    "in the train carriage",
    "at the petrol station",
    "on the park bench",
    "in the lecture theatre",
    "at the university library",
    "on the hotel rooftop",
    "in the children’s ward",
    "at the exhibition booth",
    "on the cabin porch",
    "in the retail showroom",
    "at the charity event",
    "on the marina dock",
    "in the emergency room",
    "at the post office",
    "on the charging station",
    "in the locker room",
    "at the street corner",
    "on the basketball court",
    "in the subway carriage",
    "at the convenience store",
    "on the veranda porch",
    "in the record store",
    "at the ice cream stand",
    "on the dockside crane",
    "in the greenhouse interior",
    "at the valet parking",
    "on the cobblestone street"
]